### ISSUE TITLE
Add helper to work with temporarily visible UI parts like forms

### ISSUE THREAD

**Issue by mstahv** [viritin/mopo#1]
It is common that UI contains a part like form that dissappears after save. In case one asserts UI content immediately after this form, on a content that is already on the screen, and extra waits or asserts are needed. There would be a room for some helper where one could for example provide an "input script of a form" with one lambda expression and the helper would then do an implicit wait that the content is removed from the UI.

Very quick draft of the API:
```java
new DialogPw(page.locator("#my-form")).accessAndExpectToHide(()-> {
    page.getByLabel("firsName").fill("Simon");
    page.getByText("Save").click();
    // DialogPw to do implicit
    // assertThat(page.locator("#my-form")).not().isAttached();
});
// Here it would be safe to assert that already visible component
// has changed its content        
```

**Comment by simasch** [comment]
This doesn't feel intuitive. I would prefer a wait when the button is clicked

**Comment by mstahv** [comment]
That would be the #2. 

I think I'll try both approaches. Success of this depends a lot about good naming.

**Comment by mstahv** [comment]
Changed the approach a bit, but the same principle. Added a "driveIn" helper method to Mopo :-) And yes, I'm very keen to find better naming. Althought, having this kind of analogy can make it easier for people to learn using it.
